In [16]:
import sys 
sys.path.append('../MIDSEMS/M1/M1/env')

from random_maze import randomMaze

In [17]:
import gym
import numpy as np
from numpy import random
from numpy.core.fromnumeric import argmax
from math import exp,log,sqrt
import matplotlib.pyplot as plt 
import math


# default values acc to ques

In [123]:
pi = np.ones((3,4))
theta = math.pow(10,-10)
gamma = 0.99
r = -0.04
t = True
f = False

# dynamics function acc to row, column, action

In [114]:
P = [[[[
            [0.8, 0, r,f],
            [0.1, 0, r,f],
            [0.1,1,r,f]
        ],
        [
            [0.8,1,r,f],
            [0.1,0,r,f],
            [0.1,4,r,f]
        ],
        [
            [0.8,4,r,f],
            [0.1,1,r,f],
            [0.1,0,r,f]
        ],
        [
            [0.8,0,r,f],
            [0.1,0,r,f],
            [0.1,4,r,f],
        ]
    ],
    [
        [
            [0.8, 1, r,f],
            [0.1, 2, r,f],
            [0.1,0,r,f]
        ],
        [
            [0.8,2,r,f],
            [0.1,1,r,f],
            [0.1,1,r,f]
        ],
        [
            [0.8,1,r,f],
            [0.1,2,r,f],
            [0.1,0,r,f]
        ],
        [
            [0.8,0,r,f],
            [0.1,1,r,f],
            [0.1,1,r,f],
        ]
    ],
    [
        [
            [0.8, 2, r,f],
            [0.1, 3, 1,t],
            [0.1, 1,r,f]
        ],
        [
            [0.8,3,1,t],
            [0.1,2,r,f],
            [0.1,6,r,f]
        ],
        [
            [0.8,6,r,f],
            [0.1,3,1,t],
            [0.1,1,r,f]
        ],
        [
            [0.8,1,r,f],
            [0.1,2,r,f],
            [0.1,6,r,f],
        ]
    ],
    [
        [
            [1,3,0,t]
        ],
        [
            [1,3,0,t]

        ],
        [
            [1,3,0,t]
        ],
        [
            [1,3,0,t]
        ],
    ]
],
    [
    [
        [
            [0.8, 0, r,f],
            [0.1, 4, r,f],
            [0.1,4,r,f]
        ],
        [
            [0.8,4,r,f],
            [0.1,0,r,f],
            [0.1,8,r,f]
        ],
        [
            [0.8,8,r,f],
            [0.1,4,r,f],
            [0.1,4,r,f]
        ],
        [
            [0.8,4,r,f],
            [0.1,0,r,f],
            [0.1,8,r,f],
        ]
    ],
    [
            [],[],[],[]
    ],
    [
        [
            [0.8, 2, r,f],
            [0.1, 7, -1,t],
            [0.1, 6,r,f]
        ],
        [
            [0.8,7,-1,t],
            [0.1,2,r,f],
            [0.1,10,r,f]
        ],
        [
            [0.8,10,r,f],
            [0.1,7,-1,t],
            [0.1,6,r,f]
        ],
        [
            [0.8,6,r,f],
            [0.1,2,r,f],
            [0.1,10,r,f],
        ]
    ],
    [
        [
            [1,7,0,t]
        ],
        [
            [1,7,0,t]

        ],
        [
            [1,7,0,t]
        ],
        [
            [1,7,0,t]
        ],
    ]
],
    [
    [
        [
            [0.8, 4, r,f],
            [0.1, 8, r,f],
            [0.1,9,r,f]
        ],
        [
            [0.8,9,r,f],
            [0.1,8,r,f],
            [0.1,4,r,f]
        ],
        [
            [0.8,8,r,f],
            [0.1,8,r,f],
            [0.1,9,r,f]
        ],
        [
            [0.8,8,r,f],
            [0.1,8,r,f],
            [0.1,4,r,f],
        ]
    ],
    [
        [
            [0.8, 9, r,f],
            [0.1, 8, r,f],
            [0.1,10,r,f]
        ],
        [
            [0.8,10,r,f],
            [0.1,9,r,f],
            [0.1,9,r,f]
        ],
        [
            [0.8,9,r,f],
            [0.1,8,r,f],
            [0.1,10,r,f]
        ],
        [
            [0.8,8,r,f],
            [0.1,9,r,f],
            [0.1,9,r,f],
        ]
    ],
    [
        [
            [0.8, 6, r,f],
            [0.1, 9, r,f],
            [0.1, 11,r,f]
        ],
        [
            [0.8,11,r,f],
            [0.1,10,r,f],
            [0.1,6,r,f]
        ],
        [
            [0.8,10,r,f],
            [0.1,9,r,f],
            [0.1,11,r,f]
        ],
        [
            [0.8,9,r,f],
            [0.1,10,r,f],
            [0.1,6,r,f],
        ]
    ],
    [
        [
            [0.8, 7, -1,t],
            [0.1, 10, r,f],
            [0.1, 11,r,f]
        ],
        [
            [0.8,11,r,f],
            [0.1,11,r,f],
            [0.1,7,-1,t]
        ],
        [
            [0.8,11,r,f],
            [0.1,10,r,f],
            [0.1,11,r,f]
        ],
        [
            [0.8,10,r,f],
            [0.1,11,r,f],
            [0.1,7,-1,t],
        ]
    ]
],
]

# testing the policy evaluation

In [124]:
def policyEvaluation(pi,P,gamma,theta):
    vold = np.zeros((3,4))
    while 1:
        vnew = np.zeros((3,4))
        for i in range(3):
            for j in range(4):
                for a in range(4):
                    temp = np.zeros((3,4))
                    for k in range(len(P[i][j][a])):
                        p = P[i][j][a][k][0]
                        s = P[i][j][a][k][1]
                        r = P[i][j][a][k][2]
                        f = P[i][j][a][k][3]
#                         print(p,s,r,f)
                        
                        temp[i][j] += p*(r+gamma*vold[s//4][s%4])
                    if a == pi[i][j]:
                        vnew += temp
                    else:
                        vnew += 0
        if(np.amax(vnew-vold))<theta:
            break
        vold = vnew
    return vnew

In [125]:
print(policyEvaluation(pi,P,gamma,theta))

[[ 0.59060986  0.73376182  0.79243253  0.        ]
 [-0.11228586  0.         -0.79585788  0.        ]
 [-0.59650777 -0.69481087 -0.73214578 -0.75210329]]


# policy improvement and testing it

In [126]:
def policyImprovement(v,P,gamma):
    Q = np.zeros((3,4,4))
    pi = np.zeros((3,4))
    for i in range(3):
        for j in range(4):
            for a in range(4):
                for k in range(len(P[i][j][a])):
                    p = P[i][j][a][k][0]
                    s = P[i][j][a][k][1]
                    r = P[i][j][a][k][2]
                    f = P[i][j][a][k][3]
#                         print(p,s,r,f)
                    
                    Q[i][j][a] += p*(r+gamma*v[s//4][s%4])
        
    for i in range(3):
        for j in range(4):
            pi[i][j] = np.argmax(Q[i][j])
    return pi

In [127]:
print(policyImprovement(policyEvaluation(pi,P,gamma,theta),P,gamma))

[[1. 1. 1. 0.]
 [0. 0. 0. 0.]
 [0. 3. 3. 2.]]


# policy iteration

In [128]:
def policyIteration(pi,P,gamma,theta):
#     pi = random.randint(0,4,size = (3,4))
    cnt = 0
    while 1:
        cnt+=1
        piold = pi
        v = policyEvaluation(pi,P,gamma,theta)
        pi = policyImprovement(v,P,gamma)
        if np.all(piold==pi):
            break
            
    return v,pi,cnt

In [120]:
policyIteration(pi,P,gamma,theta)

(array([[0.82442985, 0.89286374, 0.95464233, 0.        ],
        [0.76427487, 0.        , 0.68820946, 0.        ],
        [0.69763948, 0.63906542, 0.60613373, 0.38186228]]),
 array([[1., 1., 1., 0.],
        [0., 0., 0., 0.],
        [0., 3., 0., 3.]]),
 4)

# Value Iteration

In [129]:
def valueIteration(P,gamma,theta):
    cnt = 0
    v = np.zeros((3,4))
    while 1:
        cnt += 1
        Q = np.zeros((3,4,4))
        for i in range(3):
            for j in range(4):
                for a in range(4):
                    for k in range(len(P[i][j][a])):
                        p = P[i][j][a][k][0]
                        s = P[i][j][a][k][1]
                        r = P[i][j][a][k][2]
                        f = P[i][j][a][k][3]
                        
                        Q[i][j][a] += p*(r+gamma*v[s//4][s%4])
        maxi = 0
        for i in range(3):
            for  j in range(4):
                maxi = max(maxi,abs(v[i][j]-np.amax(Q[i][j])))
        if maxi<theta:
            break
        
        for i in range(3):
            for j in range(4):
                v[i][j] = np.amax(Q[i][j])
                pi[i][j] = np.argmax(Q[i][j])
    return v,pi,cnt

In [122]:
valueIteration(P,gamma,theta)

(array([[0.82442985, 0.89286374, 0.95464233, 0.        ],
        [0.76427487, 0.        , 0.68820946, 0.        ],
        [0.69763948, 0.63906542, 0.60613373, 0.38186228]]),
 array([[1., 1., 1., 0.],
        [0., 0., 0., 0.],
        [0., 3., 0., 3.]]),
 38)